name: Deploy site on Githab pages

on:
  push:
    branches:
      - src

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_PAGES_BRANCH: master
          GH_PAGES_CNAME: none
          PELICAN_CONFIG_FILE: publishconf.py
          PELICAN_THEME_FOLDER: themes/Flex
